name = "catala-lean"
version = "0.1.0"
defaultTargets = ["CatalaLean"]

[[lean_lib]]
name = "CatalaLean"
math = false

[[require]]
name = "Mathlib"
scope = "leanprover"
gitRef = "v4.33.1"
git = "https://github.com/leanprover-community/mathlib4"
